name: Build Debug APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install buildozer cython

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Create Android license file
      run: |
        mkdir -p $ANDROID_HOME/licenses
        echo -e "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license
        ls -l $ANDROID_HOME/licenses

    - name: Build debug APK
      run: buildozer android debug

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dev-browser-debug
        path: |
          bin/*.apk
          
          .buildozer/buildozer.log
